### ISSUE TITLE
No way to construct consumer-tag when declaring consumer

### ISSUE THREAD

**Issue by Fildrance** [rabbit-link/rabbit-link#29]
When declaring consumer config through **LinkConsumerBuilder**, there is no way to set certain consumer-tag. Consumer-tag may be very useful for debugging in microservice scenario with local debugging is done in conjunction with test environment (therefore there might be mix of local connections and connections from test k8s, for example, or other developer local debugging).
Example of good consumer tag to solve such misunderstanding is 
* {assembly.name}:{assembly.version}:{machine.name}:{ConsumerId}
Therefore there will be (in rabbit-mq management web-ui) at least two markers, indicating who exactly is consuming queue - version (local is usually 1.0.0.0) and machine name.

**Comment by Fildrance** [comment]
I am a little bit confused as there is no contribution guide. I implemented this feature (made branch from master as it is ahead) - but it seems like i have no access to push branches. Can you please provide some guidance on that matter?

**Comment by RaveNoX** [comment]
Hi, there's not contribution guide, just create new pull request.

Thanks.

**Comment by RaveNoX** [comment]
Closed by merging #32
Should be available in v0.14 after NuGet.org finish processing it.
